---
version: "3"

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
        - ../:/var/www
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
    networks:
        - app_network
    depends_on:
        - webapp
        - api.orders

  webapp:
    image: webapp:latest
    container_name: webapp
    ports:
      - 3000:3000
    depends_on:
      - api.orders
      - mariadb
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - ./webapp:/webapp
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app_network

  api.orders:
    image: api-orders:latest
    container_name: api-orders
    ports:
      - 5001:5001
    build:
      context: ./api.orders
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./api.orders:/api.orders
    environment:
      - CHOKIDAR_USEPOLLING=true
      - MYSQL_USER=interviewer
      - MYSQL_PASSWORD=changeme
      - MYSQL_HOST=172.17.0.1
      - MYSQL_PORT=3306
    networks:
      - app_network
  
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: marz
      MYSQL_USER: interviewer
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_PASSWORD: changeme
    restart: on-failure
    volumes:
     - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql
     - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
